### ISSUE TITLE
Développement mobile du MVP V0.2

### ISSUE THREAD

**Issue by alisonsayarath** [ferrandine/global#3]
Comme nous le savons, ce vendredi nous avons la soutenance de mi-parcours 🥇 Afin de clarifier les choses, posons ici le cadre des écrans que nous allons présenter.

**Parcours / Liste des écrans pour vendredi :** 
- [ ] Choix du vêtement ([ref](https://github.com/eazip/eazip-app-ios/issues/4))
- [ ] Choix de la retouche ([ref](https://github.com/eazip/eazip-app-ios/issues/5))
- [x] Liste des couturiers à proximité ([ref](https://github.com/eazip/eazip-app-ios/issues/6))
- [x] Page d'un couturier ([ref](https://github.com/eazip/eazip-app-ios/issues/7))
- [x] Liste des retouches ([ref](https://github.com/eazip/eazip-app-ios/issues/8))
- [ ] Page d'une retouche ([ref](https://github.com/eazip/eazip-app-ios/issues/9))
